stage('Push Images') {
    steps {
        withCredentials([usernamePassword(
            credentialsId: 'dockerhub-creds',
            usernameVariable: 'DOCKER_USER',
            passwordVariable: 'DOCKER_PASS'
        )]) {
            sh '''
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push rajeshpawar012/shopnow-backend:latest
            docker push rajeshpawar012/shopnow-frontend:latest
            '''
        }
    }
}
